"""Assemble one bundle per entry from the entry graph."""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from pathlib import Path

from . import conf
from .compiler import CompileError, transform
from .discovery import AppTemplates
from .graph import KIND_ELEMENT, EntryGraph
from .naming import template_key

#: Written at the top of every bundle, so nobody hand-edits a build artifact.
HEADER = "/* generated by scoped_css — do not edit; see ARCHITECTURE.md */\n"


@dataclass
class BundleRecord:
    entry: str
    bundle: str  # static path, e.g. "testapp/scoped_css/page.3f9a1c2d.css"
    attr: str  # page attribute
    sources: list[str]  # absolute paths
    source_mtime: float
    # --- detail the manifest schema does not require, kept for --list and the checks ------
    path: Path | None = None  # the bundle on disk
    source_details: list[dict] = field(default_factory=list)  # {"path", "template", "scope", "kind"}
    warnings: list[str] = field(default_factory=list)


def build_entry(app_templates: AppTemplates, graph: EntryGraph) -> BundleRecord | None:
    """Order: entry's own css first, then partials in DFS order; dedupe by (path, scope);
    .css verbatim, .module.css via compiler.transform; banner `/* source: <path> [scope: <attr>] */`;
    filename `<entry_key>.<sha256[:8]>.css`; remove stale bundles for the same entry.
    Return None when the entry graph contains no stylesheets."""
    app = app_templates.app
    entry_key = template_key(app.label, graph.entry)
    warnings = list(graph.warnings)

    chunks: list[str] = []
    sources: list[str] = []
    details: list[dict] = []
    seen: set[tuple[str, str]] = set()
    newest = 0.0

    for name, scope, kind in graph.ordered_sources:
        ref = app_templates.templates.get(name)
        if ref is None:  # outside the app: an edge, never a source
            continue
        for stylesheet in ref.stylesheets:
            key = (str(stylesheet), scope)
            if key in seen:
                continue
            seen.add(key)
            is_module = stylesheet.name.endswith(".module.css")
            label = _source_label(app_templates, stylesheet)
            try:
                text = stylesheet.read_text(encoding="utf-8")
            except OSError as exc:  # pragma: no cover - raced away mid-build
                warnings.append(f"scoped_css: cannot read {stylesheet}: {exc}")
                continue

            if is_module:
                try:
                    css, report = transform(
                        text,
                        scope,
                        source_name=label,
                        self_match=(kind == KIND_ELEMENT),
                        outer_selectors=conf.get("OUTER_SELECTORS"),
                    )
                except CompileError as exc:
                    # One bad stylesheet must not abort the app's build.
                    warnings.append(f"scoped_css: {exc}")
                    continue
                warnings.extend(f"{label}: {w}" for w in report.warnings)
                banner = f"/* source: {label} [scope: {scope}] */"
            else:
                css, banner = text, f"/* source: {label} */"

            chunks.append(f"{banner}\n{css.strip()}\n")
            sources.append(str(stylesheet))
            details.append({"path": str(stylesheet), "template": name, "scope": scope, "kind": kind})
            newest = max(newest, stylesheet.stat().st_mtime)

    output_dir = app_templates.output_dir
    if not chunks:
        # The entry lost its stylesheets: any bundle left from a previous build is stale.
        _remove_stale(output_dir, entry_key, keep=None)
        return None

    content = HEADER + "\n".join(chunks)
    digest = hashlib.sha256(content.encode("utf-8")).hexdigest()[:8]
    filename = f"{entry_key}.{digest}.css"

    output_dir.mkdir(parents=True, exist_ok=True)
    bundle_path = output_dir / filename
    if not bundle_path.exists() or bundle_path.read_text(encoding="utf-8") != content:
        bundle_path.write_text(content, encoding="utf-8")
    _remove_stale(output_dir, entry_key, keep=filename)

    return BundleRecord(
        entry=graph.entry,
        bundle=f"{app.label}/scoped_css/{filename}",
        attr=graph.attr,
        sources=sources,
        source_mtime=newest,
        path=bundle_path,
        source_details=details,
        warnings=warnings,
    )


def _source_label(app_templates: AppTemplates, stylesheet: Path) -> str:
    """Banner label: the stylesheet's path relative to the app's templates/ dir.

    Relative, not absolute: the bundle's bytes decide its content hash, and that hash must not
    depend on where the checkout happens to live.
    """
    try:
        return stylesheet.relative_to(app_templates.templates_dir).as_posix()
    except ValueError:  # pragma: no cover
        return stylesheet.name


def _remove_stale(output_dir: Path, entry_key: str, keep: str | None) -> None:
    """Delete previously built bundles for the same entry."""
    if not output_dir.is_dir():
        return
    for old in output_dir.glob(f"{entry_key}.*.css"):
        if old.name == keep:
            continue
        # `page.<hash>.css` only — never `page.something.else.css` from another entry key.
        stem = old.name[len(entry_key) + 1 : -len(".css")]
        if "." in stem:
            continue
        try:
            old.unlink()
        except OSError:  # pragma: no cover
            pass
